//Copyright © 2024, Dénes Derhán.
//Distributed under the MIT license (https://opensource.org/license/mit).
#pragma once
#define LOGBENCH_VERSION_MAJOR 0
#define LOGBENCH_VERSION_MINOR 8
#define LOGBENCH_VERSION_PATCH 2

#define LOGBENCH_STRINGIFY_IMPL(X) #X
#define LOGBENCH_STRINGIFY(X) LOGBENCH_STRINGIFY_IMPL(X)

#define LOGBENCH_VERSION LOGBENCH_STRINGIFY(\
	LOGBENCH_VERSION_MAJOR)"."\
	LOGBENCH_STRINGIFY(LOGBENCH_VERSION_MINOR)"."\
	LOGBENCH_STRINGIFY(LOGBENCH_VERSION_PATCH)
