//Copyright © 2024, Dénes Derhán.
//Distributed under the MIT license (https://opensource.org/license/mit).
#pragma once
#define LOGBENCHLIB_VERSION_MAJOR 0
#define LOGBENCHLIB_VERSION_MINOR 13
#define LOGBENCHLIB_VERSION_PATCH 6

#define LOGBENCHLIB_STRINGIFY_IMPL(X) #X
#define LOGBENCHLIB_STRINGIFY(X) LOGBENCHLIB_STRINGIFY_IMPL(X)

#define LOGBENCHLIB_VERSION LOGBENCHLIB_STRINGIFY(\
	LOGBENCHLIB_VERSION_MAJOR)"."\
	LOGBENCHLIB_STRINGIFY(LOGBENCHLIB_VERSION_MINOR)"."\
	LOGBENCHLIB_STRINGIFY(LOGBENCHLIB_VERSION_PATCH)
